### ISSUE TITLE
Confused about example given example section in lecture notes 2.2

### ISSUE THREAD

**Issue by DiegoAvena** [alexhkurz/programming-languages-2019#4]
In the example section of lecture notes 2.2, near the bottom, I am not sure if the first instance of the example:

((𝜆𝑥.(𝜆𝑦.𝑥)𝑀)𝑁

is missing a parenthesis somewhere? I was thinking maybe there should be 1 more parenthesis to make it ((𝜆𝑥.(𝜆𝑦.𝑥))𝑀)𝑁? 

Also, is this part just trying to say then that the result, (𝜆𝑦.𝑀)𝑁 can be renamed to just M?

**Comment by alexhkurz** [comment]
Thanks for spotting this ... corrected now.

> On Sep 5, 2019, at 10:49, Diego Avena <notifications@github.com> wrote:
> 
> In the example section of lecture notes 2.2, near the bottom, I am not sure if the first instance of the example:
> 
> ((𝜆𝑥.(𝜆𝑦.𝑥)𝑀)𝑁
> 

you are right, parentheses need always balance out ...

> is missing a parenthesis somewhere? I was thinking maybe there should be 1 more parenthesis to make it ((𝜆𝑥.(𝜆𝑦.𝑥))𝑀)𝑁?

this is what I had in mind ... but I think it may be better to use our rules for dropping parentheses and simplify it to (𝜆𝑥.𝜆𝑦.𝑥) 𝑀 𝑁 ... this is easier to read

> Also, is this part just trying to say then that the result, (𝜆𝑦.𝑀)𝑁 can be renamed to just M?

Only because we know that M does not contain y ... does this make sense?

A

**Comment by DiegoAvena** [comment]
Ok ya that clears things up for me on this part then. Thanks!
